import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Image from 'next/image'
import logo from '../img/logo.png'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="wrap">
        <header>
        <h1><Link className='logo' href="/"><Image src={logo} width={100} /></Link></h1>
            <nav>
              <ul className="depth1">
                <li><Link className='bold' href="/pages/0_1_board">대시보드</Link></li>
                <li><Link className='bold' href="#">근무편성</Link>
                    <ul className="depth2">
                      <li><Link className='bold blur' href="/pages/1_1_written">편성표 작성</Link></li>
                      <li><Link className='bold blur' href="/pages/1_2_attend">출근부</Link></li>
                    </ul>
                </li>
                <li><Link className='bold' href="/pages/2_0_planning">연간점검계획</Link></li>
                <li><Link className='bold' href="#">시설 점검표</Link>
                  <ul className="depth2">
                      <li><Link className='bold blur' href="/pages/3_1_check_list">점검결과</Link></li>
                      <li><Link className='bold blur' href="/pages/3_2_check">점검</Link></li>
                  </ul>
                </li>
                <li><Link className='bold' href="#">재고관리</Link>
                  <ul className="depth2">
                      <li><Link className='bold blur' href="/pages/4_1_stock_setting">재고등록</Link></li>
                      <li><Link className='bold blur' href="/pages/4_2_stock_manage">재고관리</Link></li>
                  </ul>
                </li>
                <li><Link className='bold' href="#">일일업무보고</Link>
                  <ul className="depth2">
                      <li><Link className='bold blur' href="/pages/5_1_report_writting">보고서작성</Link></li>
                      <li><Link className='bold blur' href="/pages/5_2_report_list">보고서확인</Link></li>
                  </ul>
                </li>
                <li><Link className='bold' href="#">시스템관리</Link>
                  <ul className="depth2">
                      <li><Link className='bold blur' href="/pages/6_1_system_enroll">사용자등록</Link></li>
                      <li><Link className='bold blur' href="/pages/6_2_system_qr">큐알코드등록</Link></li>
                  </ul>
                </li>
              </ul>
            </nav>
        </header>
        {children}
        <footer>
          <h1>푸터</h1>
        </footer>
      </div>
      </body> 
    </html>
  )
}